version: 0.2

phases:
  install:
    commands:
      - echo Install dependencies ...
      - apt-get install tree
  pre_build:
    commands:
      - echo Pre build ...
      - cd docs
      - mkdir -p build/html
      - echo "text" > build/html/output.txt
  build:
    commands:
      - echo Build ...
      - ls -al
      - tree
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/html
  discard-paths: yes