version: 0.2

phases:
  install:
    commands:
      - echo Install dependencies ...
  pre_build:
    commands:
      - echo Pre build ...
      - cd docs
  build:
    commands:
      - echo Build ...
      - ls -al
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/html
  discard-paths: yes