version: 0.2

phases:
  install:
    commands:
      - echo Install dependencies ...
      - pip install -r requirements-docs.txt
      - pip install doc2dash
      - pip install .
  pre_build:
    commands:
      - echo Pre build ...
      - cd docs
      - make html
  build:
    commands:
      - echo Build ...
      - echo Build started on `date`
      - doc2dash -A build/html -f
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/html
  discard-paths: yes